using System.Net;
using System.Text.Json;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Refit;
using Relay.Domain.Messaging;
using Relay.Providers.Abstractions;

namespace Relay.Providers.Email.Postal;

/// <summary>
/// Delivers email through Postal.
/// </summary>
/// <remarks>
/// The whole job of this class is translation: Postal's status codes and error
/// bodies in, Relay's <see cref="DeliveryResult"/> out. There is no retry logic,
/// no rate limiting, no circuit breaker and no metrics here — those are applied
/// uniformly by the decorator chain (ADR 0007), and a provider that implemented
/// its own would be fighting the chain rather than using it.
/// </remarks>
internal sealed class PostalProvider : IMessageProvider, IReceiptQueryable
{
    private static readonly ProviderDescriptor Self = new(
        ProviderId.Create("email.postal").Value,
        ChannelType.Email,
        ProviderCapabilities.ReturnsMessageId
        | ProviderCapabilities.PushesDeliveryReceipts
        | ProviderCapabilities.QueryableReceipts
        | ProviderCapabilities.NativeIdempotency
        | ProviderCapabilities.ReportsRetryAfter,

        // Email bounces are generated by the receiving server, which may queue and
        // retry for hours before giving up. Waiting six hours before declaring a
        // message unresolved is not caution, it is how long the answer takes.
        ExpectedReceiptWindow: TimeSpan.FromHours(6));

    private readonly IPostalApi _api;
    private readonly PostalOptions _options;
    private readonly ILogger<PostalProvider> _logger;

    public PostalProvider(
        IPostalApi api,
        IOptions<PostalOptions> options,
        ILogger<PostalProvider> logger)
    {
        _api = api;
        _options = options.Value;
        _logger = logger;
    }

    public ProviderDescriptor Descriptor => Self;

    public async Task<DeliveryResult> SendAsync(
        DeliveryRequest request,
        CancellationToken cancellationToken)
    {
        var payload = new PostalSendRequest
        {
            From = _options.FromAddress,
            To = request.Recipient.Address,
            Subject = request.Body.Subject,
            Body = request.Body.Content,
            IdempotencyKey = request.IdempotencyKey.Value,
        };

        IApiResponse<PostalSendResponse> response;
        try
        {
            response = await _api.SendAsync(payload, cancellationToken).ConfigureAwait(false);
        }
        catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested)
        {
            // The caller stopped us. This is the one exception the contract lets
            // through, and the `when` clause is what makes the distinction: an
            // HttpClient timeout also surfaces as OperationCanceledException, but
            // with our token still un-cancelled. Without the guard, a timeout would
            // propagate as cancellation and the pipeline would treat a slow
            // provider as a shutdown signal.
            throw;
        }
        catch (Exception exception) when (IsTimeout(exception))
        {
            return TimedOut();
        }
        catch (HttpRequestException exception)
        {
            return DeliveryResult.TransientFailure($"Could not reach Postal: {exception.Message}");
        }

        return Interpret(response);
    }

    public async Task<ReceiptStatus> QueryReceiptAsync(
        string providerMessageId,
        CancellationToken cancellationToken)
    {
        IApiResponse<PostalMessageStatusResponse> response;
        try
        {
            response = await _api.GetStatusAsync(providerMessageId, cancellationToken)
                .ConfigureAwait(false);
        }
        catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested)
        {
            throw;
        }
        catch (Exception exception) when (exception is OperationCanceledException or HttpRequestException)
        {
            // The sweeper asks again later. Reporting Failed here would turn a
            // network blip into a delivery outcome.
            return ReceiptStatus.Unknown;
        }

        if (response.StatusCode is HttpStatusCode.NotFound)
        {
            return ReceiptStatus.Unknown;
        }

        return response.Content?.Status?.ToLowerInvariant() switch
        {
            "delivered" => ReceiptStatus.Delivered,
            "bounced" or "failed" or "rejected" => ReceiptStatus.Failed,
            "queued" or "sending" or "sent" => ReceiptStatus.Pending,
            _ => ReceiptStatus.Unknown,
        };
    }

    /// <summary>
    /// Whether an exception represents "the clock ran out" rather than "the call failed".
    /// </summary>
    /// <remarks>
    /// The chain is walked rather than the outer type matched, because a
    /// client-side timeout does not have one type: depending on where in the stack
    /// the deadline fires it arrives as a <see cref="TimeoutException"/>, as a
    /// <see cref="TaskCanceledException"/> wrapping one, or wrapped again inside an
    /// <see cref="HttpRequestException"/>.
    /// <para>
    /// Getting this wrong is not cosmetic. A timeout misread as a transient failure
    /// records an attempt asserting the message was not sent, when it may well have
    /// been.
    /// </para>
    /// </remarks>
    private static bool IsTimeout(Exception exception)
    {
        for (Exception? current = exception; current is not null; current = current.InnerException)
        {
            if (current is TimeoutException)
            {
                return true;
            }
        }

        // A TaskCanceledException with no timeout in the chain only reaches here
        // when our own token was not the cause — a caller's cancellation is matched
        // by an earlier clause and rethrown.
        return exception is TaskCanceledException;
    }

    private DeliveryResult TimedOut() => DeliveryResult.Timeout(
        $"Postal did not respond within {_options.Timeout.TotalSeconds:0}s.");

    private DeliveryResult Interpret(IApiResponse<PostalSendResponse> response)
    {
        // Refit does not throw when the method returns IApiResponse — including
        // when the failure was a client-side timeout rather than a reply. The
        // exception is attached to the response instead, so a timeout arrives here
        // looking like an ordinary unsuccessful call and has to be recognised
        // before the status code is consulted. It has no status code to consult.
        if (response.Error is { } failure && IsTimeout(failure))
        {
            return TimedOut();
        }

        if (response.IsSuccessful)
        {
            string? id = response.Content?.Id;

            if (string.IsNullOrWhiteSpace(id))
            {
                // The descriptor promises ReturnsMessageId. A success without one
                // would leave a message that can never be reconciled, silently, so
                // it is treated as a transient failure and retried rather than
                // recorded as sent.
                _logger.LogWarning(
                    "Postal accepted a message without returning an id. "
                    + "The message cannot be reconciled and will be retried.");

                return DeliveryResult.TransientFailure(
                    "Postal accepted the message but returned no message id.");
            }

            return DeliveryResult.Accepted(id);
        }

        string reason = DescribeFailure(response);

        return response.StatusCode switch
        {
            HttpStatusCode.TooManyRequests =>
                DeliveryResult.RateLimited(reason, RetryAfter(response)),

            // 4xx other than 429 means Postal understood us and said no. Retrying
            // asks the same question and gets the same answer, so the message
            // fails now rather than after exhausting its budget.
            HttpStatusCode.BadRequest
                or HttpStatusCode.UnprocessableEntity
                or HttpStatusCode.Forbidden
                or HttpStatusCode.NotFound => DeliveryResult.Rejected(reason),

            // 401 is a configuration fault, not a property of this message. It is
            // transient so the message survives a credential rotation; the log line
            // is what tells an operator the retries are pointless until they act.
            HttpStatusCode.Unauthorized => DeliveryResult.TransientFailure(reason),

            _ => DeliveryResult.TransientFailure(reason),
        };
    }

    private static TimeSpan? RetryAfter(IApiResponse response)
    {
        System.Net.Http.Headers.RetryConditionHeaderValue? header =
            response.Headers?.RetryAfter;

        if (header is null)
        {
            return null;
        }

        if (header.Delta is { } delta)
        {
            return delta;
        }

        return header.Date is { } date && date > DateTimeOffset.UtcNow
            ? date - DateTimeOffset.UtcNow
            : null;
    }

    private string DescribeFailure(IApiResponse response)
    {
        string? body = response.Error is ApiException failure ? failure.Content : null;
        string detail = ExtractErrorDetail(body) ?? response.ReasonPhrase ?? "no detail";

        // Postal echoes the submitted request back inside its error payloads,
        // including the bearer token. Failure reasons are logged and shown to
        // operators, so passing that through would put the API key in the log
        // store. Masking here rather than at the log sink because the value has
        // already left the provider by then, and every other sink would need the
        // same rule.
        return Mask(detail);
    }

    private static string? ExtractErrorDetail(string? body)
    {
        if (string.IsNullOrWhiteSpace(body))
        {
            return null;
        }

        try
        {
            PostalErrorResponse? parsed =
                JsonSerializer.Deserialize<PostalErrorResponse>(body);

            return parsed?.Message ?? parsed?.Error ?? Truncate(body);
        }
        catch (JsonException)
        {
            // Postal returned something that is not its documented error shape.
            // The body is still the most useful thing to report, truncated so a
            // stray HTML error page does not become a log entry.
            return Truncate(body);
        }
    }

    private string Mask(string detail) =>
        string.IsNullOrEmpty(_options.ApiKey)
            ? detail
            : detail.Replace(_options.ApiKey, "***", StringComparison.Ordinal);

    private static string Truncate(string value) =>
        value.Length <= 500 ? value : string.Concat(value.AsSpan(0, 500), "…");
}
