// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Relay.Infrastructure.Persistence;

#nullable disable

namespace Relay.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RelayDbContext))]
    [Migration("20260828132237_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Relay.Domain.Messaging.DeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("attempted_at");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("outcome");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_id");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("provider_message_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("message_id")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "ProviderMessageId")
                        .HasDatabaseName("ix_delivery_attempts_provider_message_id")
                        .HasFilter("provider_message_id IS NOT NULL");

                    b.HasIndex("message_id", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_delivery_attempts_message_sequence");

                    b.ToTable("delivery_attempts", (string)null);
                });

            modelBuilder.Entity("Relay.Domain.Messaging.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentProviderId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("current_provider_id");

                    b.Property<DateTimeOffset?>("DispatchStartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("dispatch_started_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DispatchStartedAt")
                        .HasDatabaseName("ix_messages_stuck_dispatching")
                        .HasFilter("status = 'Dispatching'");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_messages_idempotency_key");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("ix_messages_awaiting_receipt")
                        .HasFilter("status = 'Sent'");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_messages_status_created_at");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Relay.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Relay.Domain.Messaging.DeliveryAttempt", b =>
                {
                    b.HasOne("Relay.Domain.Messaging.Message", null)
                        .WithMany("Attempts")
                        .HasForeignKey("message_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Relay.Domain.Messaging.Message", b =>
                {
                    b.OwnsOne("Relay.Domain.Messaging.MessageBody", "Body", b1 =>
                        {
                            b1.Property<Guid>("MessageId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasMaxLength(500000)
                                .HasColumnType("character varying(500000)")
                                .HasColumnName("body");

                            b1.Property<string>("Subject")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("subject");

                            b1.HasKey("MessageId");

                            b1.ToTable("messages");

                            b1.WithOwner()
                                .HasForeignKey("MessageId");
                        });

                    b.OwnsOne("Relay.Domain.Messaging.Recipient", "Recipient", b1 =>
                        {
                            b1.Property<Guid>("MessageId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("recipient_address");

                            b1.Property<string>("Channel")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("channel");

                            b1.HasKey("MessageId");

                            b1.ToTable("messages");

                            b1.WithOwner()
                                .HasForeignKey("MessageId");
                        });

                    b.Navigation("Body")
                        .IsRequired();

                    b.Navigation("Recipient")
                        .IsRequired();
                });

            modelBuilder.Entity("Relay.Domain.Messaging.Message", b =>
                {
                    b.Navigation("Attempts");
                });
#pragma warning restore 612, 618
        }
    }
}
